name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Agregar permisos explícitos para el workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Detener el build si hay errores de Python sintaxis
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Salidas de advertencias de estilo de código
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Ejecutar las pruebas desde el directorio test/
        python -m unittest discover -s test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert jupyter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate documentation
      run: |
        # Convertir notebook a HTML
        jupyter nbconvert --to html scraping.ipynb
        # Crear directorio de docs
        mkdir -p docs
        mv scraping.html docs/index.html
        # Copiar README a docs
        cp README.md docs/
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs        # La carpeta que contiene los archivos a desplegar
        branch: gh-pages    # La rama donde se publicará
        clean: true         # Eliminar archivos anteriores
